import type { Metadata } from "next";
import "./globals.css";
import { Plus_Jakarta_Sans, Bricolage_Grotesque } from "next/font/google";

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-Plus_Jakarta_Sans",
  subsets: ["latin"],
});



const Bricolage = Bricolage_Grotesque({
  variable: "--font-Bricolage_Grotesque",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jakartaSans.className} ${Bricolage.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
